-- ═══════════════════════════════════════════════════════════════════
-- GANAPORTAL DATABASE SCHEMA
-- Generated by: ARCH-002 (Database Architect)
-- Database: PostgreSQL 16
-- Tables: ~120
-- ═══════════════════════════════════════════════════════════════════

-- Enable extensions
CREATE EXTENSION IF NOT EXISTS "uuid-ossp";
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 1: AUTHENTICATION & USERS (3 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE users (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    email VARCHAR(255) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(50) NOT NULL CHECK (role IN ('admin', 'hr', 'accountant', 'employee', 'external_ca')),
    company_id UUID NOT NULL,
    employee_id UUID,
    is_active BOOLEAN DEFAULT TRUE,
    is_verified BOOLEAN DEFAULT FALSE,
    last_login TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID,
    updated_by UUID
);

CREATE TABLE user_sessions (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES users(id),
    refresh_token VARCHAR(512) NOT NULL,
    expires_at TIMESTAMP WITH TIME ZONE NOT NULL,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE user_audit_log (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID REFERENCES users(id),
    action VARCHAR(100) NOT NULL,
    entity_type VARCHAR(100),
    entity_id UUID,
    old_values JSONB,
    new_values JSONB,
    ip_address INET,
    user_agent TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 2: ORGANIZATION (6 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE company_profile (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(255) NOT NULL,
    legal_name VARCHAR(255),
    cin VARCHAR(50),
    pan VARCHAR(20),
    tan VARCHAR(20),
    gstin VARCHAR(20),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100) DEFAULT 'Karnataka',
    pincode VARCHAR(10),
    country VARCHAR(100) DEFAULT 'India',
    phone VARCHAR(20),
    email VARCHAR(255),
    website VARCHAR(255),
    logo_url VARCHAR(500),
    financial_year_start INTEGER DEFAULT 4,
    currency VARCHAR(3) DEFAULT 'INR',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE company_statutory (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    pf_establishment_id VARCHAR(50),
    pf_registration_date DATE,
    esi_code VARCHAR(50),
    esi_registration_date DATE,
    pt_registration_number VARCHAR(50),
    professional_tax_state VARCHAR(50) DEFAULT 'Karnataka',
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE departments (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20),
    parent_id UUID REFERENCES departments(id),
    head_employee_id UUID,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, code)
);

CREATE TABLE designations (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20),
    level INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, code)
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 3: EMPLOYEES (9 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE employees (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    employee_code VARCHAR(50) NOT NULL,
    first_name VARCHAR(100) NOT NULL,
    middle_name VARCHAR(100),
    last_name VARCHAR(100) NOT NULL,
    date_of_birth DATE,
    gender VARCHAR(20),
    marital_status VARCHAR(20),
    nationality VARCHAR(50) DEFAULT 'Indian',
    blood_group VARCHAR(10),
    profile_photo_url VARCHAR(500),
    department_id UUID REFERENCES departments(id),
    designation_id UUID REFERENCES designations(id),
    reporting_to UUID REFERENCES employees(id),
    employment_status VARCHAR(50) DEFAULT 'active',
    employment_type VARCHAR(50) DEFAULT 'full_time',
    date_of_joining DATE NOT NULL,
    date_of_leaving DATE,
    probation_end_date DATE,
    confirmation_date DATE,
    notice_period_days INTEGER DEFAULT 30,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID,
    updated_by UUID,
    deleted_at TIMESTAMP WITH TIME ZONE,
    UNIQUE(company_id, employee_code)
);

CREATE TABLE employee_contact (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    personal_email VARCHAR(255),
    work_email VARCHAR(255),
    personal_phone VARCHAR(20),
    work_phone VARCHAR(20),
    emergency_contact_name VARCHAR(100),
    emergency_contact_phone VARCHAR(20),
    emergency_contact_relation VARCHAR(50),
    current_address_line1 VARCHAR(255),
    current_address_line2 VARCHAR(255),
    current_city VARCHAR(100),
    current_state VARCHAR(100),
    current_pincode VARCHAR(10),
    permanent_address_line1 VARCHAR(255),
    permanent_address_line2 VARCHAR(255),
    permanent_city VARCHAR(100),
    permanent_state VARCHAR(100),
    permanent_pincode VARCHAR(10),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE employee_identity (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    pan VARCHAR(20),
    aadhaar VARCHAR(20),
    passport_number VARCHAR(50),
    passport_expiry DATE,
    uan VARCHAR(20),
    pf_number VARCHAR(50),
    esi_number VARCHAR(50),
    voter_id VARCHAR(50),
    driving_license VARCHAR(50),
    driving_license_expiry DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE employee_bank (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    bank_name VARCHAR(100) NOT NULL,
    branch_name VARCHAR(100),
    account_number VARCHAR(50) NOT NULL,
    ifsc_code VARCHAR(20) NOT NULL,
    account_type VARCHAR(50) DEFAULT 'savings',
    is_primary BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE employee_documents (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    document_type VARCHAR(100) NOT NULL,
    document_name VARCHAR(255) NOT NULL,
    file_path VARCHAR(500) NOT NULL,
    file_size INTEGER,
    mime_type VARCHAR(100),
    is_verified BOOLEAN DEFAULT FALSE,
    verified_by UUID,
    verified_at TIMESTAMP WITH TIME ZONE,
    expiry_date DATE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 4: PAYROLL (12 tables) - CRITICAL COMPLIANCE
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE salary_components (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(50) NOT NULL,
    component_type VARCHAR(50) NOT NULL CHECK (component_type IN ('earning', 'deduction', 'employer_contribution')),
    calculation_type VARCHAR(50) NOT NULL CHECK (calculation_type IN ('fixed', 'percentage', 'formula')),
    percentage_of VARCHAR(50),
    is_taxable BOOLEAN DEFAULT TRUE,
    is_part_of_ctc BOOLEAN DEFAULT TRUE,
    is_pf_applicable BOOLEAN DEFAULT FALSE,
    is_esi_applicable BOOLEAN DEFAULT FALSE,
    is_pt_applicable BOOLEAN DEFAULT FALSE,
    display_order INTEGER,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, code)
);

CREATE TABLE employee_salary (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_id UUID NOT NULL REFERENCES employees(id),
    effective_from DATE NOT NULL,
    effective_to DATE,
    ctc_annual DECIMAL(15,2) NOT NULL,
    ctc_monthly DECIMAL(15,2) NOT NULL,
    gross_monthly DECIMAL(15,2) NOT NULL,
    basic_monthly DECIMAL(15,2) NOT NULL,
    pf_wage DECIMAL(15,2),
    esi_applicable BOOLEAN DEFAULT FALSE,
    tax_regime VARCHAR(10) DEFAULT 'new' CHECK (tax_regime IN ('new', 'old')),
    is_current BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID
);

CREATE TABLE employee_salary_components (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    employee_salary_id UUID NOT NULL REFERENCES employee_salary(id),
    salary_component_id UUID NOT NULL REFERENCES salary_components(id),
    amount DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE payroll_runs (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    month INTEGER NOT NULL CHECK (month >= 1 AND month <= 12),
    year INTEGER NOT NULL,
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'processing', 'completed', 'cancelled')),
    total_employees INTEGER,
    total_gross DECIMAL(15,2),
    total_deductions DECIMAL(15,2),
    total_net DECIMAL(15,2),
    total_employer_pf DECIMAL(15,2),
    total_employer_esi DECIMAL(15,2),
    processed_at TIMESTAMP WITH TIME ZONE,
    processed_by UUID,
    finalized_at TIMESTAMP WITH TIME ZONE,
    finalized_by UUID,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, month, year)
);

CREATE TABLE payslips (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    payroll_run_id UUID NOT NULL REFERENCES payroll_runs(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    working_days INTEGER,
    paid_days DECIMAL(5,2),
    lop_days DECIMAL(5,2) DEFAULT 0,
    gross_salary DECIMAL(15,2) NOT NULL,
    total_earnings DECIMAL(15,2) NOT NULL,
    total_deductions DECIMAL(15,2) NOT NULL,
    net_salary DECIMAL(15,2) NOT NULL,
    -- PF Details
    employee_pf DECIMAL(15,2) DEFAULT 0,
    employer_pf DECIMAL(15,2) DEFAULT 0,
    employer_eps DECIMAL(15,2) DEFAULT 0,
    employer_epf DECIMAL(15,2) DEFAULT 0,
    -- ESI Details
    employee_esi DECIMAL(15,2) DEFAULT 0,
    employer_esi DECIMAL(15,2) DEFAULT 0,
    -- Tax Details
    tds DECIMAL(15,2) DEFAULT 0,
    professional_tax DECIMAL(15,2) DEFAULT 0,
    -- Status
    status VARCHAR(50) DEFAULT 'generated',
    pdf_url VARCHAR(500),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(employee_id, month, year)
);

CREATE TABLE payslip_components (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    payslip_id UUID NOT NULL REFERENCES payslips(id),
    salary_component_id UUID NOT NULL REFERENCES salary_components(id),
    component_type VARCHAR(50) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- PF Monthly Data (for ECR generation)
CREATE TABLE pf_monthly_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    payslip_id UUID REFERENCES payslips(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    uan VARCHAR(20),
    pf_wage DECIMAL(15,2) NOT NULL,
    employee_pf DECIMAL(15,2) NOT NULL,
    employer_eps DECIMAL(15,2) NOT NULL,
    employer_epf DECIMAL(15,2) NOT NULL,
    total_employer DECIMAL(15,2) NOT NULL,
    ncp_days INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(employee_id, month, year)
);

-- ESI Monthly Data
CREATE TABLE esi_monthly_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    payslip_id UUID REFERENCES payslips(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    esi_number VARCHAR(50),
    gross_salary DECIMAL(15,2) NOT NULL,
    employee_esi DECIMAL(15,2) NOT NULL,
    employer_esi DECIMAL(15,2) NOT NULL,
    total_esi DECIMAL(15,2) NOT NULL,
    ip_days INTEGER DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(employee_id, month, year)
);

-- TDS Monthly Data
CREATE TABLE tds_monthly_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    payslip_id UUID REFERENCES payslips(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    tax_regime VARCHAR(10) NOT NULL,
    projected_annual_income DECIMAL(15,2),
    projected_annual_tax DECIMAL(15,2),
    tds_deducted DECIMAL(15,2) NOT NULL,
    cumulative_tds DECIMAL(15,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(employee_id, month, year)
);

-- Professional Tax Data
CREATE TABLE pt_data (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    employee_id UUID NOT NULL REFERENCES employees(id),
    payslip_id UUID REFERENCES payslips(id),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    state VARCHAR(50) DEFAULT 'Karnataka',
    gross_salary DECIMAL(15,2) NOT NULL,
    pt_amount DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(employee_id, month, year)
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 5: ACCOUNTING (10 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE account_groups (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20),
    group_type VARCHAR(50) NOT NULL CHECK (group_type IN ('asset', 'liability', 'equity', 'income', 'expense')),
    parent_id UUID REFERENCES account_groups(id),
    is_system BOOLEAN DEFAULT FALSE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE accounts (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    account_group_id UUID NOT NULL REFERENCES account_groups(id),
    name VARCHAR(100) NOT NULL,
    code VARCHAR(20) NOT NULL,
    account_type VARCHAR(50) NOT NULL,
    opening_balance DECIMAL(15,2) DEFAULT 0,
    current_balance DECIMAL(15,2) DEFAULT 0,
    currency VARCHAR(3) DEFAULT 'INR',
    is_system BOOLEAN DEFAULT FALSE,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, code)
);

CREATE TABLE journal_entries (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    entry_number VARCHAR(50) NOT NULL,
    entry_date DATE NOT NULL,
    narration TEXT,
    reference_type VARCHAR(50),
    reference_id UUID,
    total_debit DECIMAL(15,2) NOT NULL,
    total_credit DECIMAL(15,2) NOT NULL,
    status VARCHAR(50) DEFAULT 'posted',
    is_ai_generated BOOLEAN DEFAULT FALSE,
    ai_confidence DECIMAL(5,2),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    created_by UUID,
    UNIQUE(company_id, entry_number)
);

CREATE TABLE journal_entry_lines (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    journal_entry_id UUID NOT NULL REFERENCES journal_entries(id),
    account_id UUID NOT NULL REFERENCES accounts(id),
    debit_amount DECIMAL(15,2) DEFAULT 0,
    credit_amount DECIMAL(15,2) DEFAULT 0,
    narration TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 6: AR - CUSTOMERS & INVOICES (6 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE customers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    customer_code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(20),
    gstin VARCHAR(20),
    pan VARCHAR(20),
    billing_address_line1 VARCHAR(255),
    billing_address_line2 VARCHAR(255),
    billing_city VARCHAR(100),
    billing_state VARCHAR(100),
    billing_pincode VARCHAR(10),
    place_of_supply VARCHAR(100),
    credit_limit DECIMAL(15,2),
    credit_days INTEGER DEFAULT 30,
    outstanding_amount DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, customer_code)
);

CREATE TABLE invoices (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    customer_id UUID NOT NULL REFERENCES customers(id),
    invoice_number VARCHAR(50) NOT NULL,
    invoice_date DATE NOT NULL,
    due_date DATE,
    place_of_supply VARCHAR(100),
    is_inter_state BOOLEAN DEFAULT FALSE,
    subtotal DECIMAL(15,2) NOT NULL,
    cgst_amount DECIMAL(15,2) DEFAULT 0,
    sgst_amount DECIMAL(15,2) DEFAULT 0,
    igst_amount DECIMAL(15,2) DEFAULT 0,
    total_gst DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) NOT NULL,
    amount_paid DECIMAL(15,2) DEFAULT 0,
    balance_due DECIMAL(15,2),
    status VARCHAR(50) DEFAULT 'draft' CHECK (status IN ('draft', 'sent', 'partial', 'paid', 'overdue', 'cancelled')),
    notes TEXT,
    terms TEXT,
    pdf_url VARCHAR(500),
    journal_entry_id UUID REFERENCES journal_entries(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, invoice_number)
);

CREATE TABLE invoice_line_items (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    invoice_id UUID NOT NULL REFERENCES invoices(id),
    description TEXT NOT NULL,
    hsn_sac_code VARCHAR(20),
    quantity DECIMAL(10,2) DEFAULT 1,
    unit VARCHAR(20),
    rate DECIMAL(15,2) NOT NULL,
    amount DECIMAL(15,2) NOT NULL,
    gst_rate DECIMAL(5,2) DEFAULT 18,
    cgst_amount DECIMAL(15,2) DEFAULT 0,
    sgst_amount DECIMAL(15,2) DEFAULT 0,
    igst_amount DECIMAL(15,2) DEFAULT 0,
    line_total DECIMAL(15,2) NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 7: AP - VENDORS & BILLS (6 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE vendors (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    vendor_code VARCHAR(50) NOT NULL,
    name VARCHAR(255) NOT NULL,
    contact_person VARCHAR(100),
    email VARCHAR(255),
    phone VARCHAR(20),
    gstin VARCHAR(20),
    pan VARCHAR(20),
    address_line1 VARCHAR(255),
    address_line2 VARCHAR(255),
    city VARCHAR(100),
    state VARCHAR(100),
    pincode VARCHAR(10),
    vendor_type VARCHAR(50),
    tds_section VARCHAR(20),
    tds_rate DECIMAL(5,2),
    outstanding_amount DECIMAL(15,2) DEFAULT 0,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, vendor_code)
);

CREATE TABLE bills (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    vendor_id UUID NOT NULL REFERENCES vendors(id),
    bill_number VARCHAR(100) NOT NULL,
    bill_date DATE NOT NULL,
    due_date DATE,
    vendor_invoice_number VARCHAR(100),
    vendor_invoice_date DATE,
    subtotal DECIMAL(15,2) NOT NULL,
    cgst_amount DECIMAL(15,2) DEFAULT 0,
    sgst_amount DECIMAL(15,2) DEFAULT 0,
    igst_amount DECIMAL(15,2) DEFAULT 0,
    total_gst DECIMAL(15,2) DEFAULT 0,
    tds_section VARCHAR(20),
    tds_rate DECIMAL(5,2),
    tds_amount DECIMAL(15,2) DEFAULT 0,
    total_amount DECIMAL(15,2) NOT NULL,
    amount_paid DECIMAL(15,2) DEFAULT 0,
    balance_due DECIMAL(15,2),
    status VARCHAR(50) DEFAULT 'draft',
    is_ai_extracted BOOLEAN DEFAULT FALSE,
    ai_confidence DECIMAL(5,2),
    journal_entry_id UUID REFERENCES journal_entries(id),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 8: GST COMPLIANCE (4 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE hsn_sac_codes (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    code VARCHAR(20) NOT NULL UNIQUE,
    description TEXT NOT NULL,
    code_type VARCHAR(10) CHECK (code_type IN ('HSN', 'SAC')),
    gst_rate DECIMAL(5,2) DEFAULT 18,
    is_active BOOLEAN DEFAULT TRUE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE gst_returns (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    return_type VARCHAR(20) NOT NULL CHECK (return_type IN ('GSTR1', 'GSTR3B')),
    month INTEGER NOT NULL,
    year INTEGER NOT NULL,
    filing_period VARCHAR(20),
    status VARCHAR(50) DEFAULT 'draft',
    total_taxable_value DECIMAL(15,2),
    total_cgst DECIMAL(15,2),
    total_sgst DECIMAL(15,2),
    total_igst DECIMAL(15,2),
    total_tax DECIMAL(15,2),
    filed_date DATE,
    arn_number VARCHAR(50),
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    updated_at TIMESTAMP WITH TIME ZONE DEFAULT NOW(),
    UNIQUE(company_id, return_type, month, year)
);

-- ═══════════════════════════════════════════════════════════════════
-- SECTION 9: AI PROCESSING (6 tables)
-- ═══════════════════════════════════════════════════════════════════

CREATE TABLE ai_providers (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    name VARCHAR(50) NOT NULL UNIQUE,
    provider_type VARCHAR(50) NOT NULL,
    model VARCHAR(100) NOT NULL,
    priority INTEGER NOT NULL,
    is_active BOOLEAN DEFAULT TRUE,
    api_key_set BOOLEAN DEFAULT FALSE,
    last_used TIMESTAMP WITH TIME ZONE,
    total_requests INTEGER DEFAULT 0,
    total_cost DECIMAL(10,4) DEFAULT 0,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE ai_requests (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID REFERENCES company_profile(id),
    provider_id UUID REFERENCES ai_providers(id),
    request_type VARCHAR(100) NOT NULL,
    prompt_hash VARCHAR(64),
    input_tokens INTEGER,
    output_tokens INTEGER,
    confidence DECIMAL(5,2),
    cost DECIMAL(10,6),
    latency_ms INTEGER,
    success BOOLEAN DEFAULT TRUE,
    error_message TEXT,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

CREATE TABLE ai_processing_queue (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    company_id UUID NOT NULL REFERENCES company_profile(id),
    entity_type VARCHAR(100) NOT NULL,
    entity_id UUID NOT NULL,
    action VARCHAR(100) NOT NULL,
    ai_output JSONB,
    confidence DECIMAL(5,2) NOT NULL,
    status VARCHAR(50) DEFAULT 'pending' CHECK (status IN ('pending', 'approved', 'rejected', 'auto_executed')),
    reviewed_by UUID,
    reviewed_at TIMESTAMP WITH TIME ZONE,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- ═══════════════════════════════════════════════════════════════════
-- INDEXES
-- ═══════════════════════════════════════════════════════════════════

-- Users
CREATE INDEX idx_users_company_id ON users(company_id);
CREATE INDEX idx_users_email ON users(email);

-- Employees
CREATE INDEX idx_employees_company_id ON employees(company_id);
CREATE INDEX idx_employees_department ON employees(department_id);
CREATE INDEX idx_employees_status ON employees(employment_status);

-- Payroll
CREATE INDEX idx_payroll_runs_company_period ON payroll_runs(company_id, year, month);
CREATE INDEX idx_payslips_employee ON payslips(employee_id);
CREATE INDEX idx_payslips_period ON payslips(year, month);
CREATE INDEX idx_pf_monthly_period ON pf_monthly_data(year, month);
CREATE INDEX idx_esi_monthly_period ON esi_monthly_data(year, month);

-- Accounting
CREATE INDEX idx_journal_entries_company ON journal_entries(company_id);
CREATE INDEX idx_journal_entries_date ON journal_entries(entry_date);
CREATE INDEX idx_journal_lines_account ON journal_entry_lines(account_id);

-- Invoices
CREATE INDEX idx_invoices_customer ON invoices(customer_id);
CREATE INDEX idx_invoices_date ON invoices(invoice_date);
CREATE INDEX idx_invoices_status ON invoices(status);

-- Bills
CREATE INDEX idx_bills_vendor ON bills(vendor_id);
CREATE INDEX idx_bills_date ON bills(bill_date);

-- GST
CREATE INDEX idx_gst_returns_period ON gst_returns(company_id, year, month);

-- AI
CREATE INDEX idx_ai_queue_status ON ai_processing_queue(status);
CREATE INDEX idx_ai_queue_company ON ai_processing_queue(company_id);

-- ═══════════════════════════════════════════════════════════════════
-- SEED DATA
-- ═══════════════════════════════════════════════════════════════════

-- Insert common HSN/SAC codes for IT services
INSERT INTO hsn_sac_codes (code, description, code_type, gst_rate) VALUES
('998311', 'Management consulting services', 'SAC', 18),
('998312', 'Business consulting services', 'SAC', 18),
('998313', 'IT consulting and support services', 'SAC', 18),
('998314', 'IT design and development services', 'SAC', 18),
('998315', 'Hosting and IT infrastructure services', 'SAC', 18),
('998316', 'IT infrastructure and network management', 'SAC', 18),
('998319', 'Other IT services', 'SAC', 18);

-- Insert AI providers
INSERT INTO ai_providers (name, provider_type, model, priority) VALUES
('Claude', 'anthropic', 'claude-3-5-sonnet-20241022', 1),
('Gemini', 'google', 'gemini-1.5-pro', 2),
('GPT-4', 'openai', 'gpt-4-turbo', 3),
('Llama', 'together', 'meta-llama/Llama-3-70b', 4);

-- ═══════════════════════════════════════════════════════════════════
-- END OF SCHEMA
-- ═══════════════════════════════════════════════════════════════════
