"""
SQLAlchemy models package.
"""
from app.models.user import User
from app.models.employee import Employee, EmployeeContact, EmployeeIdentity, EmployeeBank, EmployeeEmployment
from app.models.department import Department, Designation
from app.models.employee_document import EmployeeDocument, DocumentType
from app.models.edms import Folder, FolderPermissionRecord, FolderPermission, Document, DocumentVersion, DocumentStatus
from app.models.onboarding import (
    OnboardingTemplate,
    OnboardingTemplateItem,
    OnboardingChecklist,
    OnboardingTask,
    OnboardingComment,
    OnboardingStatus,
    TaskStatus,
    TaskCategory,
)
from app.models.leave import (
    LeaveType,
    LeaveBalance,
    LeaveApplication,
    LeaveApprovalHistory,
    Holiday,
    LeaveStatus,
    LeaveAccrualType,
)
from app.models.timesheet import (
    Project,
    ProjectTask,
    Timesheet,
    TimesheetEntry,
    TimesheetApprovalHistory,
    TimesheetStatus,
    EntryType,
)
from app.models.payroll import (
    SalaryComponent,
    SalaryStructure,
    SalaryStructureComponent,
    EmployeeSalary,
    PayrollRun,
    Payslip,
    LoanAdvance,
    LoanRepayment,
    ComponentType,
    CalculationType,
    PayrollStatus,
    LoanType,
    LoanStatus,
)
from app.models.statutory import (
    CompanyProfile,
    CompanyStatutory,
    CompanyBankAccount,
    AuthorizedSignatory,
    PFFiling,
    PFFilingDetail,
    ESIFiling,
    ESIFilingDetail,
    TDSChallan,
    TDSFiling,
    TDSFilingDetail,
    SalaryDisbursement,
    SalaryDisbursementDetail,
    FilingStatus,
    DisbursementStatus,
    TransferType,
)
from app.models.ai import (
    AIRequest,
    AIFeedback,
    AIPromptTemplate,
    DocumentExtractionResult,
    AIRequestType,
    AIModel,
)
from app.models.accounting import (
    AccountGroup,
    Account,
    AccountingPeriod,
    JournalEntry,
    JournalEntryLine,
    AccountBalance,
    AccountGroupType,
    AccountType,
    JournalEntryStatus,
    ReferenceType,
)
from app.models.currency import (
    Currency,
    ExchangeRate,
    ForexTransaction,
    ExchangeRateSource,
)
from app.models.customer import (
    Customer,
    Invoice,
    InvoiceLineItem,
    PaymentReceipt,
    PaymentReceiptAllocation,
    CustomerType,
    InvoiceType,
    InvoiceStatus,
    SupplyType,
    PaymentStatus,
    PaymentMode,
)
from app.models.vendor import (
    Vendor,
    VendorBill,
    VendorBillLineItem,
    VendorPayment,
    VendorPaymentAllocation,
    VendorType,
    TDSSection,
    BillStatus,
    VendorPaymentStatus,
    PaymentMode as VendorPaymentMode,
)
from app.models.bank import (
    BankAccount,
    BankTransaction,
    BankStatement,
    BankStatementLine,
    PettyCash,
    PettyCashEntry,
    CashFlowMapping,
    BankAccountType,
    StatementUploadType,
    StatementStatus,
    MatchStatus,
    TransactionType,
    PettyCashEntryType,
    CashFlowCategory,
)
from app.models.gst import (
    GSTReturn,
    GSTR1Data,
    GSTR3BSummary,
    HSNSACCode,
    HSNSummary,
    ITCReconciliation,
    GSTReturnType,
    GSTReturnStatus,
    GSTInvoiceType,
    HSNCodeType,
)
from app.models.tds import (
    TDSDeduction,
    TDSChallan,
    TDSCertificate,
    TDS26QReturn,
    TDSThreshold,
    TDSDepositStatus,
    TDSCertificateStatus,
    TDS26QStatus,
)
from app.models.reports import (
    SavedReport,
    ReportSchedule,
    ReportTemplate,
    ReportType,
    ReportFormat,
    ReportScheduleFrequency,
)
from app.models.crm import (
    Lead,
    LeadActivity,
    LeadStageHistory,
    AIFollowupSuggestion,
    LeadSource,
    LeadStage,
    LeadPriority,
    ActivityType,
    ActivityOutcome,
)
from app.models.ai_assistant import (
    AIConversation,
    AIMessage,
    AIAction,
    AIInsight as AIAssistantInsight,
    DailyBriefing,
    QueryIntent,
    QueryModule,
    ActionStatus,
    InsightType,
    InsightPriority,
)
from app.models.project import (
    Project as ProjectManagement,
    Milestone,
    Task as ProjectTask21,
    ProjectMember,
    TaskComment,
    TaskStatusHistory,
    ProjectType,
    ProjectStatus,
    ProjectPriority,
    BillingType,
    HealthStatus,
    MilestoneStatus,
    TaskStatus as ProjectTaskStatus,
    TaskPriority as ProjectTaskPriority,
    TaskType as ProjectTaskType,
)

__all__ = [
    "User",
    "Employee",
    "EmployeeContact",
    "EmployeeIdentity",
    "EmployeeBank",
    "EmployeeEmployment",
    "Department",
    "Designation",
    "EmployeeDocument",
    "DocumentType",
    # EDMS
    "Folder",
    "FolderPermissionRecord",
    "FolderPermission",
    "Document",
    "DocumentVersion",
    "DocumentStatus",
    # Onboarding
    "OnboardingTemplate",
    "OnboardingTemplateItem",
    "OnboardingChecklist",
    "OnboardingTask",
    "OnboardingComment",
    "OnboardingStatus",
    "TaskStatus",
    "TaskCategory",
    # Leave
    "LeaveType",
    "LeaveBalance",
    "LeaveApplication",
    "LeaveApprovalHistory",
    "Holiday",
    "LeaveStatus",
    "LeaveAccrualType",
    # Timesheet
    "Project",
    "ProjectTask",
    "Timesheet",
    "TimesheetEntry",
    "TimesheetApprovalHistory",
    "TimesheetStatus",
    "EntryType",
    # Payroll
    "SalaryComponent",
    "SalaryStructure",
    "SalaryStructureComponent",
    "EmployeeSalary",
    "PayrollRun",
    "Payslip",
    "LoanAdvance",
    "LoanRepayment",
    "ComponentType",
    "CalculationType",
    "PayrollStatus",
    "LoanType",
    "LoanStatus",
    # Statutory
    "CompanyProfile",
    "CompanyStatutory",
    "CompanyBankAccount",
    "AuthorizedSignatory",
    "PFFiling",
    "PFFilingDetail",
    "ESIFiling",
    "ESIFilingDetail",
    "TDSChallan",
    "TDSFiling",
    "TDSFilingDetail",
    "SalaryDisbursement",
    "SalaryDisbursementDetail",
    "FilingStatus",
    "DisbursementStatus",
    "TransferType",
    # AI
    "AIRequest",
    "AIFeedback",
    "AIPromptTemplate",
    "DocumentExtractionResult",
    "AIRequestType",
    "AIModel",
    # Accounting
    "AccountGroup",
    "Account",
    "AccountingPeriod",
    "JournalEntry",
    "JournalEntryLine",
    "AccountBalance",
    "AccountGroupType",
    "AccountType",
    "JournalEntryStatus",
    "ReferenceType",
    # Currency
    "Currency",
    "ExchangeRate",
    "ForexTransaction",
    "ExchangeRateSource",
    # Customer/AR
    "Customer",
    "Invoice",
    "InvoiceLineItem",
    "PaymentReceipt",
    "PaymentReceiptAllocation",
    "CustomerType",
    "InvoiceType",
    "InvoiceStatus",
    "SupplyType",
    "PaymentStatus",
    "PaymentMode",
    # Vendor/AP
    "Vendor",
    "VendorBill",
    "VendorBillLineItem",
    "VendorPayment",
    "VendorPaymentAllocation",
    "VendorType",
    "TDSSection",
    "BillStatus",
    "VendorPaymentStatus",
    "VendorPaymentMode",
    # Bank & Cash
    "BankAccount",
    "BankTransaction",
    "BankStatement",
    "BankStatementLine",
    "PettyCash",
    "PettyCashEntry",
    "CashFlowMapping",
    "BankAccountType",
    "StatementUploadType",
    "StatementStatus",
    "MatchStatus",
    "TransactionType",
    "PettyCashEntryType",
    "CashFlowCategory",
    # GST
    "GSTReturn",
    "GSTR1Data",
    "GSTR3BSummary",
    "HSNSACCode",
    "HSNSummary",
    "ITCReconciliation",
    "GSTReturnType",
    "GSTReturnStatus",
    "GSTInvoiceType",
    "HSNCodeType",
    # TDS
    "TDSDeduction",
    "TDSChallan",
    "TDSCertificate",
    "TDS26QReturn",
    "TDSThreshold",
    "TDSDepositStatus",
    "TDSCertificateStatus",
    "TDS26QStatus",
    # Reports
    "SavedReport",
    "ReportSchedule",
    "ReportTemplate",
    "ReportType",
    "ReportFormat",
    "ReportScheduleFrequency",
    # CRM
    "Lead",
    "LeadActivity",
    "LeadStageHistory",
    "AIFollowupSuggestion",
    "LeadSource",
    "LeadStage",
    "LeadPriority",
    "ActivityType",
    "ActivityOutcome",
    # AI Assistant
    "AIConversation",
    "AIMessage",
    "AIAction",
    "AIAssistantInsight",
    "DailyBriefing",
    "QueryIntent",
    "QueryModule",
    "ActionStatus",
    "InsightType",
    "InsightPriority",
    # Project Management
    "ProjectManagement",
    "Milestone",
    "ProjectTask21",
    "ProjectMember",
    "TaskComment",
    "TaskStatusHistory",
    "ProjectType",
    "ProjectStatus",
    "ProjectPriority",
    "BillingType",
    "HealthStatus",
    "MilestoneStatus",
    "ProjectTaskStatus",
    "ProjectTaskPriority",
    "ProjectTaskType",
]
