"""
SQLAlchemy models package.
"""
from app.models.user import User
from app.models.employee import Employee, EmployeeContact, EmployeeIdentity, EmployeeBank, EmployeeEmployment
from app.models.department import Department, Designation
from app.models.employee_document import EmployeeDocument, DocumentType
from app.models.edms import Folder, FolderPermissionRecord, FolderPermission, Document, DocumentVersion, DocumentStatus
from app.models.onboarding import (
    OnboardingTemplate,
    OnboardingTemplateItem,
    OnboardingChecklist,
    OnboardingTask,
    OnboardingComment,
    OnboardingStatus,
    TaskStatus,
    TaskCategory,
)
from app.models.leave import (
    LeaveType,
    LeaveBalance,
    LeaveApplication,
    LeaveApprovalHistory,
    Holiday,
    LeaveStatus,
    LeaveAccrualType,
)
from app.models.timesheet import (
    Project,
    ProjectTask,
    Timesheet,
    TimesheetEntry,
    TimesheetApprovalHistory,
    TimesheetStatus,
    EntryType,
)
from app.models.payroll import (
    SalaryComponent,
    SalaryStructure,
    SalaryStructureComponent,
    EmployeeSalary,
    PayrollRun,
    Payslip,
    LoanAdvance,
    LoanRepayment,
    ComponentType,
    CalculationType,
    PayrollStatus,
    LoanType,
    LoanStatus,
)
from app.models.statutory import (
    CompanyProfile,
    CompanyStatutory,
    CompanyBankAccount,
    AuthorizedSignatory,
    PFFiling,
    PFFilingDetail,
    ESIFiling,
    ESIFilingDetail,
    TDSChallan,
    TDSFiling,
    TDSFilingDetail,
    SalaryDisbursement,
    SalaryDisbursementDetail,
    FilingStatus,
    DisbursementStatus,
    TransferType,
)
from app.models.ai import (
    AIRequest,
    AIFeedback,
    AIPromptTemplate,
    DocumentExtractionResult,
    AIRequestType,
    AIModel,
)
from app.models.accounting import (
    AccountGroup,
    Account,
    AccountingPeriod,
    JournalEntry,
    JournalEntryLine,
    AccountBalance,
    AccountGroupType,
    AccountType,
    JournalEntryStatus,
    ReferenceType,
)
from app.models.currency import (
    Currency,
    ExchangeRate,
    ForexTransaction,
    ExchangeRateSource,
)
from app.models.customer import (
    Customer,
    Invoice,
    InvoiceLineItem,
    PaymentReceipt,
    PaymentReceiptAllocation,
    CustomerType,
    InvoiceType,
    InvoiceStatus,
    SupplyType,
    PaymentStatus,
    PaymentMode,
)
from app.models.vendor import (
    Vendor,
    VendorBill,
    VendorBillLineItem,
    VendorPayment,
    VendorPaymentAllocation,
    VendorType,
    TDSSection,
    BillStatus,
    VendorPaymentStatus,
    PaymentMode as VendorPaymentMode,
)

__all__ = [
    "User",
    "Employee",
    "EmployeeContact",
    "EmployeeIdentity",
    "EmployeeBank",
    "EmployeeEmployment",
    "Department",
    "Designation",
    "EmployeeDocument",
    "DocumentType",
    # EDMS
    "Folder",
    "FolderPermissionRecord",
    "FolderPermission",
    "Document",
    "DocumentVersion",
    "DocumentStatus",
    # Onboarding
    "OnboardingTemplate",
    "OnboardingTemplateItem",
    "OnboardingChecklist",
    "OnboardingTask",
    "OnboardingComment",
    "OnboardingStatus",
    "TaskStatus",
    "TaskCategory",
    # Leave
    "LeaveType",
    "LeaveBalance",
    "LeaveApplication",
    "LeaveApprovalHistory",
    "Holiday",
    "LeaveStatus",
    "LeaveAccrualType",
    # Timesheet
    "Project",
    "ProjectTask",
    "Timesheet",
    "TimesheetEntry",
    "TimesheetApprovalHistory",
    "TimesheetStatus",
    "EntryType",
    # Payroll
    "SalaryComponent",
    "SalaryStructure",
    "SalaryStructureComponent",
    "EmployeeSalary",
    "PayrollRun",
    "Payslip",
    "LoanAdvance",
    "LoanRepayment",
    "ComponentType",
    "CalculationType",
    "PayrollStatus",
    "LoanType",
    "LoanStatus",
    # Statutory
    "CompanyProfile",
    "CompanyStatutory",
    "CompanyBankAccount",
    "AuthorizedSignatory",
    "PFFiling",
    "PFFilingDetail",
    "ESIFiling",
    "ESIFilingDetail",
    "TDSChallan",
    "TDSFiling",
    "TDSFilingDetail",
    "SalaryDisbursement",
    "SalaryDisbursementDetail",
    "FilingStatus",
    "DisbursementStatus",
    "TransferType",
    # AI
    "AIRequest",
    "AIFeedback",
    "AIPromptTemplate",
    "DocumentExtractionResult",
    "AIRequestType",
    "AIModel",
    # Accounting
    "AccountGroup",
    "Account",
    "AccountingPeriod",
    "JournalEntry",
    "JournalEntryLine",
    "AccountBalance",
    "AccountGroupType",
    "AccountType",
    "JournalEntryStatus",
    "ReferenceType",
    # Currency
    "Currency",
    "ExchangeRate",
    "ForexTransaction",
    "ExchangeRateSource",
    # Customer/AR
    "Customer",
    "Invoice",
    "InvoiceLineItem",
    "PaymentReceipt",
    "PaymentReceiptAllocation",
    "CustomerType",
    "InvoiceType",
    "InvoiceStatus",
    "SupplyType",
    "PaymentStatus",
    "PaymentMode",
    # Vendor/AP
    "Vendor",
    "VendorBill",
    "VendorBillLineItem",
    "VendorPayment",
    "VendorPaymentAllocation",
    "VendorType",
    "TDSSection",
    "BillStatus",
    "VendorPaymentStatus",
    "VendorPaymentMode",
]
